name: bookkart_author
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 20.4.1+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  #  firebase crashlytics analytics support
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  firebase_analytics: ^8.3.4

  # Used for speed up the coding and font selection
  nb_utils: ^4.4.10
  google_fonts: ^2.1.0
  file_picker: ^4.2.1

  #  used for API calling and Showing Html data
  http: ^0.13.4
  intl: ^0.17.0
  crypto: ^3.0.1
  html: 0.15.0
  flutter_html: ^2.1.5
  url_launcher: ^6.0.12

  #  Used for Images and icon
  cached_network_image: ^3.1.0+1
  flutter_vector_icons: ^1.0.0

  #  Application information
  package_info: ^2.0.2
  flutter_rating_bar: 4.0.0

  #  Used for chart
  syncfusion_flutter_charts: ^19.3.48

  # State Management Technique
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

  flutter_localizations:
    sdk: flutter
  connectivity_plus_web: ^1.2.5
  dropdown_button2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4
#flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flags/





